// Schémas partagés front/back : la même règle valide le formulaire et le body de l'API.
// Source TypeScript chargée telle quelle (type stripping de Node côté back, Vite côté front) :
// imports relatifs avec l'extension .ts, et uniquement de la syntaxe effaçable (pas d'enum, pas de namespace).
export * from './common/email.field.ts'
export * from './common/new-password.field.ts'
export * from './auth/account.dto.ts'
export * from './auth/login.dto.ts'
export * from './auth/signup.dto.ts'
export * from './auth/verify-email.dto.ts'
export * from './auth/forgot-password.dto.ts'
export * from './auth/reset-password.dto.ts'
export * from './users/weekday.ts'
export * from './users/user.dto.ts'
export * from './users/update-profile.dto.ts'
export * from './users/change-password.dto.ts'
export * from './users/update-availability.dto.ts'
export * from './users/day-availability.dto.ts'
export * from './users/managed-user.dto.ts'
export * from './users/find-users-query.dto.ts'
export * from './users/user-page.dto.ts'
export * from './users/update-user.dto.ts'
export * from './users/update-user-role.dto.ts'
export * from './users/update-user-permissions.dto.ts'
export * from './roles/permissions.ts'
export * from './roles/role.dto.ts'
export * from './roles/update-role.dto.ts'
export * from './events/participant.dto.ts'
export * from './events/guest.dto.ts'
export * from './events/event.dto.ts'
export * from './events/save-event.dto.ts'
export * from './events/answer-event.dto.ts'
export * from './events/add-guest.dto.ts'
export * from './email-domains/email-domain.dto.ts'
export * from './email-domains/save-email-domain.dto.ts'
